//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exiao.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exiao.Demo.Resources.ViewTexts", typeof(ViewTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Suppliers.
        /// </summary>
        internal static string AllSuppliers {
            get {
                return ResourceManager.GetString("AllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Group.
        /// </summary>
        internal static string AssignGroup {
            get {
                return ResourceManager.GetString("AssignGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity.
        /// </summary>
        internal static string AvailableQuantity {
            get {
                return ResourceManager.GetString("AvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Item.
        /// </summary>
        internal static string CatalogItem {
            get {
                return ResourceManager.GetString("CatalogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Item Detail.
        /// </summary>
        internal static string CatalogItemDetail {
            get {
                return ResourceManager.GetString("CatalogItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Items.
        /// </summary>
        internal static string CatalogItems {
            get {
                return ResourceManager.GetString("CatalogItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Management.
        /// </summary>
        internal static string CatalogManagement {
            get {
                return ResourceManager.GetString("CatalogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Catalog Item.
        /// </summary>
        internal static string CreateCatalogItem {
            get {
                return ResourceManager.GetString("CreateCatalogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Inventory.
        /// </summary>
        internal static string CreateInventory {
            get {
                return ResourceManager.GetString("CreateInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Supplier.
        /// </summary>
        internal static string CreateSupplier {
            get {
                return ResourceManager.GetString("CreateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Version.
        /// </summary>
        internal static string DataVersion {
            get {
                return ResourceManager.GetString("DataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        internal static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Catalog Item.
        /// </summary>
        internal static string EditCatalogItem {
            get {
                return ResourceManager.GetString("EditCatalogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Fulfillment Order.
        /// </summary>
        internal static string EditFulfillmentOrder {
            get {
                return ResourceManager.GetString("EditFulfillmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Inventory.
        /// </summary>
        internal static string EditInventory {
            get {
                return ResourceManager.GetString("EditInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supplier.
        /// </summary>
        internal static string EditSupplier {
            get {
                return ResourceManager.GetString("EditSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiao.com.
        /// </summary>
        internal static string ExiaoTitle {
            get {
                return ResourceManager.GetString("ExiaoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Data.
        /// </summary>
        internal static string ExtraData {
            get {
                return ResourceManager.GetString("ExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by name or id.
        /// </summary>
        internal static string FindByNameOrId {
            get {
                return ResourceManager.GetString("FindByNameOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by name or sku.
        /// </summary>
        internal static string FindByNameOrSku {
            get {
                return ResourceManager.GetString("FindByNameOrSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by order id or sku.
        /// </summary>
        internal static string FindByOrderIdOrSku {
            get {
                return ResourceManager.GetString("FindByOrderIdOrSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by sku.
        /// </summary>
        internal static string FindBySku {
            get {
                return ResourceManager.GetString("FindBySku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string FoStatusDelivered {
            get {
                return ResourceManager.GetString("FoStatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryConfirmed.
        /// </summary>
        internal static string FoStatusInventoryConfirmed {
            get {
                return ResourceManager.GetString("FoStatusInventoryConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string FoStatusNew {
            get {
                return ResourceManager.GetString("FoStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderCreated.
        /// </summary>
        internal static string FoStatusOrderCreated {
            get {
                return ResourceManager.GetString("FoStatusOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string FoStatusShipped {
            get {
                return ResourceManager.GetString("FoStatusShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Fulfillment Order Id.
        /// </summary>
        internal static string FrontEndFulfillmentOrderId {
            get {
                return ResourceManager.GetString("FrontEndFulfillmentOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment.
        /// </summary>
        internal static string Fulfillment {
            get {
                return ResourceManager.GetString("Fulfillment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Order.
        /// </summary>
        internal static string FulfillmentOrder {
            get {
                return ResourceManager.GetString("FulfillmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Order Detail.
        /// </summary>
        internal static string FulfillmentOrderDetail {
            get {
                return ResourceManager.GetString("FulfillmentOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Order Id.
        /// </summary>
        internal static string FulfillmentOrderId {
            get {
                return ResourceManager.GetString("FulfillmentOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Order Management.
        /// </summary>
        internal static string FulfillmentOrderManagement {
            get {
                return ResourceManager.GetString("FulfillmentOrderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Orders.
        /// </summary>
        internal static string FulfillmentOrders {
            get {
                return ResourceManager.GetString("FulfillmentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        internal static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        internal static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Details.
        /// </summary>
        internal static string InventoryDetails {
            get {
                return ResourceManager.GetString("InventoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        internal static string InventoryManagement {
            get {
                return ResourceManager.GetString("InventoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Unlimited.
        /// </summary>
        internal static string IsUnlimited {
            get {
                return ResourceManager.GetString("IsUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Lines.
        /// </summary>
        internal static string ItemLines {
            get {
                return ResourceManager.GetString("ItemLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Groups.
        /// </summary>
        internal static string MappingGroups {
            get {
                return ResourceManager.GetString("MappingGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        internal static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Variant.
        /// </summary>
        internal static string ProductVariant {
            get {
                return ResourceManager.GetString("ProductVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mappings.
        /// </summary>
        internal static string RemoveMappings {
            get {
                return ResourceManager.GetString("RemoveMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping To.
        /// </summary>
        internal static string ShippingTo {
            get {
                return ResourceManager.GetString("ShippingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Detail.
        /// </summary>
        internal static string SupplierDetail {
            get {
                return ResourceManager.GetString("SupplierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierId.
        /// </summary>
        internal static string SupplierId {
            get {
                return ResourceManager.GetString("SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Management.
        /// </summary>
        internal static string SupplierManagement {
            get {
                return ResourceManager.GetString("SupplierManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierName.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
    }
}
